<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Project;

class ProjectSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $projects = [
            [
                'title' => 'Torre Residencial Moderna - Santa Cruz',
                'slug' => 'torre-residencial-moderna-santa-cruz',
                'description' => 'Edificio residencial de alta gama que combina lujo y sostenibilidad en el corazón de la zona este de Santa Cruz, incorporando elementos arquitectónicos inspirados en la cultura chiquitana.',
                'image_path' => null,
                'category' => 'Infraestructura',
                'status' => 'Completado',
                'characteristics' => [
                    'location' => 'Santa Cruz de la Sierra',
                    'area' => '18,500 m²',
                    'duration' => '28 meses',
                    'estimation' => '$18,500,000 USD',
                    'year' => 2022,
                    'architect' => 'Arq. Carlos Mendez',
                ],
                'gallery_equirectangular' => [],
                'pdf_path' => null,
                'orientation' => 'vertical',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Hospital Oncológico Nacional - La Paz',
                'slug' => 'hospital-oncologico-nacional-la-paz',
                'description' => 'Centro médico especializado de referencia nacional ubicado en El Alto, que integra medicina tradicional aymara con tecnología de punta en un diseño bioclimático adaptado a la altura.',
                'image_path' => null,
                'category' => 'Salud',
                'status' => 'En construcción',
                'characteristics' => [
                    'location' => 'El Alto, La Paz',
                    'area' => '45,000 m²',
                    'duration' => '36 meses',
                    'estimation' => '$65,000,000 USD',
                    'year' => 2024,
                    'architect' => 'Arq. Lucía Quispe',
                ],
                'gallery_equirectangular' => [],
                'pdf_path' => null,
                'orientation' => 'vertical',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Centro Cultural Tiwanaku - Copacabana',
                'slug' => 'centro-cultural-tiwanaku-copacabana',
                'description' => 'Complejo museográfico y de investigación dedicado a la cultura Tiwanaku, ubicado en las riberas del Lago Titicaca, que reinterpreta la arquitectura precolombina con técnicas contemporáneas.',
                'image_path' => null,
                'category' => 'Cultural',
                'status' => 'Completado',
                'characteristics' => [
                    'location' => 'Copacabana, La Paz',
                    'area' => '12,000 m²',
                    'duration' => '22 meses',
                    'estimation' => '$12,000,000 USD',
                    'year' => 2021,
                    'architect' => 'Arq. Julio Condori',
                ],
                'gallery_equirectangular' => [],
                'pdf_path' => null,
                'orientation' => 'horizontal',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Planta de Procesamiento de Quinua - Oruro',
                'slug' => 'planta-de-procesamiento-de-quinua-oruro',
                'description' => 'Complejo industrial ecoeficiente para el procesamiento y valor agregado de quinua real, incorporando tecnología de punta con arquitectura inspirada en los salares de Uyuni.',
                'image_path' => null,
                'category' => 'Salud',
                'status' => 'Completado',
                'characteristics' => [
                    'location' => 'Salinas de Garci Mendoza, Oruro',
                    'area' => '8,500 m²',
                    'duration' => '18 meses',
                    'estimation' => '$8,200,000 USD',
                    'year' => 2020,
                    'architect' => 'Arq. Fernando Morales',
                ],
                'gallery_equirectangular' => [],
                'pdf_path' => null,
                'orientation' => 'horizontal',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Edificio Corporativo YPFB - Cochabamba',
                'slug' => 'edificio-corporativo-ypfb-cochabamba',
                'description' => 'Sede regional de Yacimientos Petrolíferos Fiscales Bolivianos que refleja la identidad energética del país a través de un diseño dinámico y sostenible en el valle cochabambino.',
                'image_path' => null,
                'category' => 'Institucional',
                'status' => 'En construcción',
                'characteristics' => [
                    'location' => 'Cochabamba',
                    'area' => '25,000 m²',
                    'duration' => '30 meses',
                    'estimation' => '$32,000,000 USD',
                    'year' => 2024,
                    'architect' => 'Arq. Patricia Rojas',
                ],
                'gallery_equirectangular' => [],
                'pdf_path' => null,
                'orientation' => 'vertical',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Complejo Turístico Eco-Lodge - Rurrenabaque',
                'slug' => 'complejo-turistico-eco-lodge-rurrenabaque',
                'description' => 'Conjunto de cabañas de lujo sostenible en la Amazonía boliviana, diseñadas para la observación de biodiversidad con mínimo impacto ambiental y colaboración comunitaria.',
                'image_path' => null,
                'category' => 'Institucional',
                'status' => 'Completado',
                'characteristics' => [
                    'location' => 'Rurrenabaque, Beni',
                    'area' => '15 hectáreas',
                    'duration' => '14 meses',
                    'estimation' => '$4,500,000 USD',
                    'year' => 2022,
                    'architect' => 'Arq. Miguel Ángel Vaca',
                ],
                'gallery_equirectangular' => [],
                'pdf_path' => null,
                'orientation' => 'horizontal',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Estadio Nacional de Alto Rendimiento - Sucre',
                'slug' => 'estadio-nacional-alto-rendimiento-sucre',
                'description' => 'Complejo deportivo polifuncional diseñado para entrenamiento de alto rendimiento y competencias internacionales, ubicado en la capital constitucional de Bolivia.',
                'image_path' => null,
                'category' => 'Salud',
                'status' => 'En diseño',
                'characteristics' => [
                    'location' => 'Sucre, Chuquisaca',
                    'area' => '32,000 m²',
                    'duration' => '34 meses',
                    'estimation' => '$45,000,000 USD',
                    'year' => 2025,
                    'architect' => 'Arq. Roberto Sánchez',
                ],
                'gallery_equirectangular' => [],
                'pdf_path' => null,
                'orientation' => 'horizontal',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Mercado Mayorista de Alimentos - El Alto',
                'slug' => 'mercado-mayorista-alimentos-el-alto',
                'description' => 'Centro de abastecimiento y distribución de alimentos más grande de Bolivia, diseñado como nodo logístico inteligente para optimizar la cadena de suministro alimentario.',
                'image_path' => null,
                'category' => 'Cultural',
                'status' => 'Completado',
                'characteristics' => [
                    'location' => 'Distrito 8, El Alto',
                    'area' => '42,000 m²',
                    'duration' => '26 meses',
                    'estimation' => '$28,000,000 USD',
                    'year' => 2021,
                    'architect' => 'Arq. Elena Mamani',
                ],
                'gallery_equirectangular' => [],
                'pdf_path' => null,
                'orientation' => 'horizontal',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Centro de Innovación Tecnológica - Tarija',
                'slug' => 'centro-de-innovacion-tecnologica-tarija',
                'description' => 'Hub de investigación y desarrollo tecnológico especializado en energías renovables y agricultura de precisión para los valles tarijeños y la región del Chaco.',
                'image_path' => null,
                'category' => 'Infraestructura',
                'status' => 'En construcción',
                'characteristics' => [
                    'location' => 'Tarija',
                    'area' => '16,500 m²',
                    'duration' => '24 meses',
                    'estimation' => '$22,000,000 USD',
                    'year' => 2024,
                    'architect' => 'Arq. Jorge Méndez',
                ],
                'gallery_equirectangular' => [],
                'pdf_path' => null,
                'orientation' => 'vertical',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Terminal de Buses Bimodal - Potosí',
                'slug' => 'terminal-de-buses-bimodal-potosi',
                'description' => 'Estación intermodal que integra transporte terrestre y futuro sistema de teleférico, diseñada como puerta de entrada a la ciudad patrimonial de la humanidad.',
                'image_path' => null,
                'category' => 'Infraestructura',
                'status' => 'Completado',
                'characteristics' => [
                    'location' => 'Potosí',
                    'area' => '9,800 m²',
                    'duration' => '20 meses',
                    'estimation' => '$15,000,000 USD',
                    'year' => 2023,
                    'architect' => 'Arq. Luis Fernando Correa',
                ],
                'gallery_equirectangular' => [],
                'pdf_path' => null,
                'orientation' => 'horizontal',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Complejo Habitacional Social - Montero',
                'slug' => 'complejo-habitacional-social-montero',
                'description' => 'Conjunto de viviendas de interés social que implementa nuevos modelos de densificación sostenible para ciudades intermedias del trópico boliviano.',
                'image_path' => null,
                'category' => 'Salud',
                'status' => 'Completado',
                'characteristics' => [
                    'location' => 'Montero, Santa Cruz',
                    'area' => '65,000 m²',
                    'duration' => '30 meses',
                    'estimation' => '$35,000,000 USD',
                    'year' => 2022,
                    'architect' => 'Arq. Ana María Suárez',
                ],
                'gallery_equirectangular' => [],
                'pdf_path' => null,
                'orientation' => 'horizontal',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Centro de Convenciones Internacional - Santa Cruz',
                'slug' => 'centro-de-convenciones-internacional-santa-cruz',
                'description' => 'Recinto ferial y de convenciones de clase mundial diseñado para posicionar a Santa Cruz como hub de negocios de Sudamérica, inspirado en la biodiversidad amazónica.',
                'image_path' => null,
                'category' => 'Cultural',
                'status' => 'En diseño',
                'characteristics' => [
                    'location' => 'Santa Cruz de la Sierra',
                    'area' => '85,000 m²',
                    'duration' => '42 meses',
                    'estimation' => '$120,000,000 USD',
                    'year' => 2026,
                    'architect' => 'Arq. Ricardo Paz',
                ],
                'gallery_equirectangular' => [],
                'pdf_path' => null,
                'orientation' => 'horizontal',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Planta de Tratamiento de Aguas - Cochabamba',
                'slug' => 'planta-de-tratamiento-de-aguas-cochabamba',
                'description' => 'Sistema integral de tratamiento y reutilización de aguas residuales que resuelve el déficit hídrico crónico de la región metropolitana de Cochabamba.',
                'image_path' => null,
                'category' => 'Infraestructura',
                'status' => 'En construcción',
                'characteristics' => [
                    'location' => 'Cercado, Cochabamba',
                    'area' => '28,000 m²',
                    'duration' => '32 meses',
                    'estimation' => '$85,000,000 USD',
                    'year' => 2024,
                    'architect' => 'Arq. Diego Andrade',
                ],
                'gallery_equirectangular' => [],
                'pdf_path' => null,
                'orientation' => 'horizontal',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Torre Mirador Cerro Rico - Potosí',
                'slug' => 'torre-mirador-cerro-rico-potosi',
                'description' => 'Estructura de observación y centro interpretativo que permite una experiencia única del Cerro Rico, combinando turismo responsable con preservación del patrimonio minero.',
                'image_path' => null,
                'category' => 'Salud',
                'status' => 'Completado',
                'characteristics' => [
                    'location' => 'Base del Cerro Rico, Potosí',
                    'area' => '2,500 m²',
                    'duration' => '16 meses',
                    'estimation' => '$6,500,000 USD',
                    'year' => 2021,
                    'architect' => 'Arq. Valeria Salinas',
                ],
                'gallery_equirectangular' => [],
                'pdf_path' => null,
                'orientation' => 'vertical',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Edificio Judicial Departamental - Trinidad',
                'slug' => 'edificio-judicial-departamental-trinidad',
                'description' => 'Sede de la justicia para el departamento del Beni, que reinterpreta la arquitectura moxeña con espacios diseñados para procesos judiciales modernos y humanizados.',
                'image_path' => null,
                'category' => 'Institucional',
                'status' => 'En construcción',
                'characteristics' => [
                    'location' => 'Trinidad, Beni',
                    'area' => '14,000 m²',
                    'duration' => '26 meses',
                    'estimation' => '$28,000,000 USD',
                    'year' => 2024,
                    'architect' => 'Arq. Rafael Vargas',
                ],
                'gallery_equirectangular' => [],
                'pdf_path' => null,
                'orientation' => 'vertical',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        // Insertar todos los proyectos
        foreach ($projects as $project) {
            Project::create($project);
        }
    }
}
